[package]
name = "bevy_post_process"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true, default-features = false }

[dev-dependencies]
bevy-inspector-egui = { workspace = true }

[lints]
workspace = true
